jobs:
  backport:
    if: "github.event.pull_request.merged == true\n&& !contains(github.event.pull_request.labels.*.name,\
      \ 'backport/skip')\n&& (\n  (github.event.action == 'labeled' && startsWith(github.event.label.name,\
      \ 'backport/'))\n  || (github.event.action == 'closed')\n)\n"
    name: Backport PR
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Backport Action
      uses: sqren/backport-github-action@v9.5.1
      with:
        add_original_reviewers: true
        auto_backport_label_prefix: backport/
        github_token: ${{ secrets.ACCESS_TOKEN }}
    - continue-on-error: true
      if: ${{ success() }}
      name: Info log
      run: cat ~/.backport/backport.info.log
    - continue-on-error: true
      if: ${{ failure() }}
      name: Debug log
      run: cat ~/.backport/backport.debug.log
on:
  repository_dispatch:
    types: trigger-ga___backport.yml
