jobs:
  tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "No build required"
    strategy:
      matrix:
        include:
        - args: -Dtest="**/diskstorage/hbase/*"
          java: 8
          module: hbase
          name: hbase2-diskstorage
        - args: -Dtest="**/graphdb/hbase/*"
          java: 8
          module: hbase
          name: hbase2-graphdb
        - args: -Dtest="**/hadoop/*"
          java: 8
          module: hbase
          name: hbase2-hadoop
        - args: -Dtest="**/diskstorage/hbase/*"
          install-args: -Pjava-11
          java: 11
          module: hbase
          name: hbase2-diskstorage
        - args: -Dtest="**/graphdb/hbase/*"
          install-args: -Pjava-11
          java: 11
          module: hbase
          name: hbase2-graphdb
        - args: -Dtest="**/hadoop/*"
          install-args: -Pjava-11
          java: 11
          module: hbase
          name: hbase2-hadoop
name: CI Backend Hbase
on:
  repository_dispatch:
    types: trigger-ga___ci-backend-hbase-dummy.yml
