jobs:
  tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "No build required"
    strategy:
      matrix:
        include:
        - args: -Pcassandra3-byteordered -Dtest="**/diskstorage/cql/*"
          java: 8
          module: cql
          name: byteordered-diskstorage
        - args: -Pcassandra3-murmur -Dtest="**/diskstorage/cql/*"
          java: 8
          module: cql
          name: murmur-diskstorage
        - args: -Pcassandra3-byteordered -Dtest="**/graphdb/cql/*"
          java: 8
          module: cql
          name: byteordered-graphdb
        - args: -Pcassandra3-murmur -Dtest="**/graphdb/cql/*"
          java: 8
          module: cql
          name: murmur-graphdb
        - args: -Pcassandra3-murmur -Dtest="**/hadoop/*"
          java: 8
          module: cql
          name: murmur-hadoop
        - args: -Pcassandra3-byteordered -Dtest="**/core/cql/*"
          java: 8
          module: cql
          name: byteordered-core
        - args: -Pcassandra3-murmur -Dtest="**/core/cql/*"
          java: 8
          module: cql
          name: murmur-core
        - args: -Pcassandra3-murmur-ssl -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          java: 8
          module: cql
          name: murmur-ssl
        - args: -Pcassandra3-murmur-client-auth -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          java: 8
          module: cql
          name: murmur-client-auth
        - args: -Pscylladb -Dtest="**/diskstorage/cql/*"
          java: 8
          module: cql
          name: scylladb-diskstorage
        - args: -Pscylladb -Dtest="**/graphdb/cql/*"
          java: 8
          module: cql
          name: scylladb-graphdb
        - args: -Pscylladb -Dtest="**/hadoop/*"
          java: 8
          module: cql
          name: scylladb-hadoop
        - args: -Pscylladb -Dtest="**/core/cql/*"
          java: 8
          module: cql
          name: scylladb-core
        - args: -Pcassandra3-byteordered -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: byteordered-diskstorage
        - args: -Pcassandra3-murmur -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-diskstorage
        - args: -Pcassandra3-byteordered -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: byteordered-graphdb
        - args: -Pcassandra3-murmur -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-graphdb
        - args: -Pcassandra3-murmur -Dtest="**/hadoop/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-hadoop
        - args: -Pcassandra3-byteordered -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: byteordered-core
        - args: -Pcassandra3-murmur -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-core
        - args: -Pcassandra3-murmur-ssl -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-ssl
        - args: -Pcassandra3-murmur-client-auth -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-client-auth
        - args: -Pscylladb -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: scylladb-diskstorage
        - args: -Pscylladb -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: scylladb-graphdb
        - args: -Pscylladb -Dtest="**/hadoop/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: scylladb-hadoop
        - args: -Pscylladb -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: scylladb-core
        - args: -Pcassandra4-byteordered -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: byteordered-diskstorage
        - args: -Pcassandra4-murmur -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-diskstorage
        - args: -Pcassandra4-byteordered -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: byteordered-graphdb
        - args: -Pcassandra4-murmur -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-graphdb
        - args: -Pcassandra4-murmur -Dtest="**/hadoop/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-hadoop
        - args: -Pcassandra4-byteordered -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: byteordered-core
        - args: -Pcassandra4-murmur -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-core
        - args: -Pcassandra4-murmur-ssl -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-ssl
        - args: -Pcassandra4-murmur-client-auth -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: murmur-client-auth
name: CI Backend CQL
on:
  repository_dispatch:
    types: trigger-ga___ci-backend-cql-dummy.yml
