env:
  BUILD_MAVEN_OPTS: -DskipTests=true --batch-mode --also-make
  VERIFY_MAVEN_OPTS: -Pcoverage
jobs:
  build-all:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-all -Pjanusgraph-cache -Dmaven.javadoc.skip=true
        ${{ env.BUILD_MAVEN_OPTS }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-all -Pjanusgraph-cache ${{ env.VERIFY_MAVEN_OPTS
        }}
  full-tests:
    if: github.event_name == 'push' && contains(github.event.head_commit.message,
      '[cql-tests]') || github.event_name == 'pull_request' && contains(github.event.pull_request.title,
      '[cql-tests]')
    needs: build-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-${{ matrix.module }} ${{ env.BUILD_MAVEN_OPTS
        }} ${{ matrix.install-args }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-${{ matrix.module }} -Dcassandra.docker.version='3.0.18'
        ${{ env.VERIFY_MAVEN_OPTS }} ${{ matrix.args }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - args: -Pcassandra3-byteordered -Dtest="**/diskstorage/cql/*"
          module: cql
        - args: -Pcassandra3-murmur -Dtest="**/diskstorage/cql/*"
          module: cql
        - args: -Pcassandra3-byteordered -Dtest="**/graphdb/cql/*"
          module: cql
        - args: -Pcassandra3-murmur -Dtest="**/graphdb/cql/*"
          module: cql
        - args: -Pcassandra3-murmur -Dtest="**/hadoop/*"
          module: cql
        - args: -Pcassandra3-byteordered -Dtest="**/core/cql/*"
          module: cql
        - args: -Pcassandra3-murmur -Dtest="**/core/cql/*"
          module: cql
        - args: -Pcassandra3-murmur-ssl -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          module: cql
        - args: -Pcassandra3-murmur-client-auth -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          module: cql
    timeout-minutes: 480
  tests:
    needs: build-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-${{ matrix.module }} ${{ env.BUILD_MAVEN_OPTS
        }} ${{ matrix.install-args }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-${{ matrix.module }} ${{ env.VERIFY_MAVEN_OPTS
        }} ${{ matrix.install-args }} ${{ matrix.args }}
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-reports-${{ matrix.module }}-${{ matrix.name }}
        path: target/jacoco-combined.exec
    - continue-on-error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v4
      with:
        name: codecov-cql-${{ matrix.name }}-java-${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - args: -Pcassandra3-byteordered -Dtest="**/diskstorage/cql/*"
          java: 8
          module: cql
          name: cassandra3-byteordered-diskstorage-java8
        - args: -Pcassandra3-murmur -Dtest="**/diskstorage/cql/*"
          java: 8
          module: cql
          name: cassandra3-murmur-diskstorage-java8
        - args: -Pcassandra3-byteordered -Dtest="**/graphdb/cql/*"
          java: 8
          module: cql
          name: cassandra3-byteordered-graphdb-java8
        - args: -Pcassandra3-murmur -Dtest="**/graphdb/cql/*"
          java: 8
          module: cql
          name: cassandra3-murmur-graphdb-java8
        - args: -Pcassandra3-murmur -Dtest="**/hadoop/*"
          java: 8
          module: cql
          name: cassandra3-murmur-hadoop-java8
        - args: -Pcassandra3-byteordered -Dtest="**/core/cql/*"
          java: 8
          module: cql
          name: cassandra3-byteordered-core-java8
        - args: -Pcassandra3-murmur -Dtest="**/core/cql/*"
          java: 8
          module: cql
          name: cassandra3-murmur-core-java8
        - args: -Pcassandra3-murmur-ssl -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          java: 8
          module: cql
          name: cassandra3-murmur-ssl-java8
        - args: -Pcassandra3-murmur-client-auth -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          java: 8
          module: cql
          name: cassandra3-murmur-client-auth-java8
        - args: -Pscylladb -Dtest="**/diskstorage/cql/*"
          java: 8
          module: cql
          name: cassandra3-scylladb-diskstorage-java8
        - args: -Pscylladb -Dtest="**/graphdb/cql/*"
          java: 8
          module: cql
          name: cassandra3-scylladb-graphdb-java8
        - args: -Pscylladb -Dtest="**/hadoop/*"
          java: 8
          module: cql
          name: cassandra3-scylladb-hadoop-java8
        - args: -Pscylladb -Dtest="**/core/cql/*"
          java: 8
          module: cql
          name: cassandra3-scylladb-core-java8
        - args: -Pcassandra3-byteordered -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra3-byteordered-diskstorage
        - args: -Pcassandra3-murmur -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra3-murmur-diskstorage
        - args: -Pcassandra3-byteordered -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra3-byteordered-graphdb
        - args: -Pcassandra3-murmur -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra3-murmur-graphdb
        - args: -Pcassandra3-murmur -Dtest="**/hadoop/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra3-murmur-hadoop
        - args: -Pcassandra3-byteordered -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra3-byteordered-core
        - args: -Pcassandra3-murmur -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra3-murmur-core
        - args: -Pcassandra3-murmur-ssl -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra3-murmur-ssl
        - args: -Pcassandra3-murmur-client-auth -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra3-murmur-client-auth
        - args: -Pscylladb -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: scylladb-diskstorage
        - args: -Pscylladb -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: scylladb-graphdb
        - args: -Pscylladb -Dtest="**/hadoop/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: scylladb-hadoop
        - args: -Pscylladb -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: scylladb-core
        - args: -Pcassandra4-byteordered -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra4-byteordered-diskstorage
        - args: -Pcassandra4-murmur -Dtest="**/diskstorage/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra4-murmur-diskstorage
        - args: -Pcassandra4-byteordered -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra4-byteordered-graphdb
        - args: -Pcassandra4-murmur -Dtest="**/graphdb/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra4-murmur-graphdb
        - args: -Pcassandra4-murmur -Dtest="**/hadoop/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra4-murmur-hadoop
        - args: -Pcassandra4-byteordered -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra4-byteordered-core
        - args: -Pcassandra4-murmur -Dtest="**/core/cql/*"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra4-murmur-core
        - args: -Pcassandra4-murmur-ssl -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra4-murmur-ssl
        - args: -Pcassandra4-murmur-client-auth -Dtest="**/diskstorage/cql/CQLStoreTest.java"
          install-args: -Pjava-11
          java: 11
          module: cql
          name: cassandra4-murmur-client-auth
name: CI Backend CQL
on:
  repository_dispatch:
    types: trigger-ga___ci-backend-cql.yml
