env:
  BUILD_MAVEN_OPTS: -DskipTests=true --batch-mode --also-make
jobs:
  benchmark:
    name: Performance regression check
    needs: build-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      run: pip install setuptools
    - continue-on-error: true
      run: pip install git+https://github.com/li-boxuan/ccm.git
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: mvn clean install -Pjanusgraph-benchmark ${{ env.BUILD_MAVEN_OPTS }} -Dgpg.skip=true
    - continue-on-error: true
      env:
        CCM_CLUSTER_START_DEFAULT_TIMEOUT: 300
        CCM_UPDATE_PID_DEFAULT_TIMEOUT: 300
      run: mvn verify --projects janusgraph-benchmark
    - continue-on-error: true
      name: Download previous benchmark data
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-benchmark
        path: ./cache
    - continue-on-error: true
      name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        comment-always: true
        comment-on-alert: true
        external-data-json-path: ./cache/benchmark-data.json
        fail-on-alert: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file-path: janusgraph-benchmark/benchmark.json
        tool: customSmallerIsBetter
  build-all:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-all -Pjanusgraph-cache -Dmaven.javadoc.skip=true
        ${{ env.BUILD_MAVEN_OPTS }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-all -Pjanusgraph-cache ${{ env.VERIFY_MAVEN_OPTS
        }}
name: CI Benchmark
on:
  repository_dispatch:
    types: trigger-ga___ci-benchmark.yml
permissions:
  contents: write
