env:
  BUILD_MAVEN_OPTS: -DskipTests=true --batch-mode --also-make
  VERIFY_MAVEN_OPTS: -Pcoverage
jobs:
  build-all:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-all -Pjanusgraph-cache -Dmaven.javadoc.skip=true
        ${{ env.BUILD_MAVEN_OPTS }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-all -Pjanusgraph-cache ${{ env.VERIFY_MAVEN_OPTS
        }}
  tests:
    needs: build-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-${{ matrix.module }} ${{ env.BUILD_MAVEN_OPTS
        }} ${{ matrix.install-args }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-${{ matrix.module }} ${{ env.VERIFY_MAVEN_OPTS
        }} ${{ matrix.install-args }} ${{ matrix.args }} -Dhbase.docker.uid=$(id -u)
        -Dhbase.docker.gid=$(id -g)
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-reports-${{ matrix.module }}-${{ matrix.name }}
        path: target/jacoco-combined.exec
    - continue-on-error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v4
      with:
        name: codecov-hbase-${{ matrix.name }}-java-${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - args: -Dtest="**/diskstorage/hbase/*"
          java: 8
          module: hbase
          name: hbase2-diskstorage-java8
        - args: -Dtest="**/graphdb/hbase/*"
          java: 8
          module: hbase
          name: hbase2-graphdb-java8
        - args: -Dtest="**/hadoop/*"
          java: 8
          module: hbase
          name: hbase2-hadoop-java8
        - args: -Dtest="**/diskstorage/hbase/*"
          install-args: -Pjava-11
          java: 11
          module: hbase
          name: hbase2-diskstorage
        - args: -Dtest="**/graphdb/hbase/*"
          install-args: -Pjava-11
          java: 11
          module: hbase
          name: hbase2-graphdb
        - args: -Dtest="**/hadoop/*"
          install-args: -Pjava-11
          java: 11
          module: hbase
          name: hbase2-hadoop
name: CI Backend Hbase
on:
  repository_dispatch:
    types: trigger-ga___ci-backend-hbase.yml
