jobs:
  build-all:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "No build required"
  build-java11:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "No build required"
  tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "No build required"
    strategy:
      matrix:
        include:
        - java: 8
          module: driver
        - java: 8
          module: server
        - java: 8
          module: test
        - args: -Dtest.skip.tp=false
          java: 8
          module: inmemory
        - java: 8
          module: berkeleyje
        - java: 8
          module: lucene
        - install-args: -Pjava-11
          java: 11
          module: driver
        - install-args: -Pjava-11
          java: 11
          module: server
        - install-args: -Pjava-11
          java: 11
          module: test
        - args: -Dtest.skip.tp=false
          install-args: -Pjava-11
          java: 11
          module: inmemory
        - install-args: -Pjava-11
          java: 11
          module: berkeleyje
        - install-args: -Pjava-11
          java: 11
          module: lucene
name: CI Core
on:
  repository_dispatch:
    types: trigger-ga___ci-core-dummy.yml
