env:
  BUILD_MAVEN_OPTS: -DskipTests=true --batch-mode --also-make
  VERIFY_MAVEN_OPTS: -Pcoverage
jobs:
  build-all:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-all -Pjanusgraph-cache -Dmaven.javadoc.skip=true
        ${{ env.BUILD_MAVEN_OPTS }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-all -Pjanusgraph-cache ${{ env.VERIFY_MAVEN_OPTS
        }}
  build-java11:
    needs: build-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-all -Pjava-11 -Pjanusgraph-cache
        -Dmaven.javadoc.skip=true ${{ env.BUILD_MAVEN_OPTS }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-all -Pjava-11 -Pjanusgraph-cache ${{ env.VERIFY_MAVEN_OPTS
        }}
  tests:
    needs: build-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-${{ matrix.module }} ${{ env.BUILD_MAVEN_OPTS
        }} ${{ matrix.install-args }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-${{ matrix.module }} ${{ env.VERIFY_MAVEN_OPTS
        }} ${{ matrix.install-args }} ${{ matrix.args }}
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-reports-${{ matrix.module }}-java-${{ matrix.java }}
        path: target/jacoco-combined.exec
    - continue-on-error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v4
      with:
        name: codecov-core-${{ matrix.module }}-java-${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 8
          module: core
        - java: 8
          module: driver
        - java: 8
          module: server
        - java: 8
          module: test
        - args: -Dtest.skip.tp=false
          java: 8
          module: inmemory
        - java: 8
          module: berkeleyje
        - java: 8
          module: lucene
        - install-args: -Pjava-11
          java: 11
          module: core
        - install-args: -Pjava-11
          java: 11
          module: driver
        - install-args: -Pjava-11
          java: 11
          module: server
        - install-args: -Pjava-11
          java: 11
          module: test
        - args: -Dtest.skip.tp=false
          install-args: -Pjava-11
          java: 11
          module: inmemory
        - install-args: -Pjava-11
          java: 11
          module: berkeleyje
        - install-args: -Pjava-11
          java: 11
          module: lucene
name: CI Core
on:
  repository_dispatch:
    types: trigger-ga___ci-core.yml
