env:
  BUILD_MAVEN_OPTS: -DskipTests=true --batch-mode --also-make
  STRUCTOR_VERSION: v1.13.2
  VERIFY_MAVEN_OPTS: -Pcoverage
jobs:
  build-all:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: mvn clean install --projects janusgraph-all -Pjanusgraph-cache -Dmaven.javadoc.skip=true
        ${{ env.BUILD_MAVEN_OPTS }}
    - continue-on-error: true
      run: mvn verify --projects janusgraph-all -Pjanusgraph-cache ${{ env.VERIFY_MAVEN_OPTS
        }}
  build-doc:
    needs: build-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      run: mvn clean install -Pjava-11 -pl janusgraph-doc ${{ env.BUILD_MAVEN_OPTS
        }}
    - continue-on-error: true
      run: git diff  --exit-code docs/configs/janusgraph-cfg.md
    - continue-on-error: true
      run: docker build -t doc-site:mkdocs -f docs.Dockerfile .
    - continue-on-error: true
      run: docker run --rm -v $PWD:/mkdocs doc-site:mkdocs mkdocs build
    - continue-on-error: true
      if: github.ref != 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: distribution-doc-builds
        path: site
  deploy-doc:
    if: github.ref == 'refs/heads/master'
    needs: build-doc
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - continue-on-error: true
      run: mkdir ./bin
    - continue-on-error: true
      run: curl -sfL https://raw.githubusercontent.com/traefik/structor/master/godownloader.sh
        | bash -s -- -b ./bin ${STRUCTOR_VERSION}
    - continue-on-error: true
      run: sudo ./bin/structor -o janusgraph -r janusgraph --force-edit-url --rqts-url="https://raw.githubusercontent.com/JanusGraph/janusgraph/master/requirements.txt"
        --dockerfile-url="https://raw.githubusercontent.com/JanusGraph/janusgraph/master/docs.Dockerfile"
        --dockerfile-name="https://raw.githubusercontent.com/JanusGraph/janusgraph/master/docs.Dockerfile"
        --menu.js-url="https://raw.githubusercontent.com/JanusGraph/janusgraph/master/docs/theme/structor-menu.js.gotmpl"
        --exp-branch=master --debug
    - continue-on-error: true
      run: sudo chown -R $(id -u):$(id -g) .
    - continue-on-error: true
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: master
        folder: site
        force: false
        repository-name: JanusGraph/docs.janusgraph.org
        token: ${{ secrets.ACCESS_TOKEN }}
name: CI Docs
on:
  repository_dispatch:
    types: trigger-ga___ci-docs.yml
