jobs:
  tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "No build required"
    strategy:
      matrix:
        include:
        - args: -Psolr8
          java: 8
          module: solr
          name: solr8
        - args: -Psolr8
          install-args: -Pjava-11
          java: 11
          module: solr
          name: solr8
name: CI Index Solr
on:
  repository_dispatch:
    types: trigger-ga___ci-index-solr-dummy.yml
