jobs:
  tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "No build required"
    strategy:
      matrix:
        include:
        - args: -Pelasticsearch8
          java: 8
          module: es
          name: es8
        - args: -Pelasticsearch7
          java: 8
          module: es
          name: es7
        - args: -Pelasticsearch6
          java: 8
          module: es
          name: es6
        - args: -Pelasticsearch60
          java: 8
          module: es
          name: es60
        - args: -Pelasticsearch8
          install-args: -Pjava-11
          java: 11
          module: es
          name: es8
        - args: -Pelasticsearch7
          install-args: -Pjava-11
          java: 11
          module: es
          name: es7
        - args: -Pelasticsearch6
          install-args: -Pjava-11
          java: 11
          module: es
          name: es6
        - args: -Pelasticsearch60
          install-args: -Pjava-11
          java: 11
          module: es
          name: es60
name: CI Index ES
on:
  repository_dispatch:
    types: trigger-ga___ci-index-es-dummy.yml
