jobs:
  dist-tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "No build required"
    strategy:
      matrix:
        include:
        - args: ''
          java: 8
        - args: -Pjava-11
          java: 11
name: CI Release
on:
  repository_dispatch:
    types: trigger-ga___ci-release-dummy.yml
