env:
  LATEST_RELEASE: 1.0
jobs:
  tagging:
    if: '!contains(github.event.release.tag_name, ''-'') && !github.event.release.prerelease'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: GET DOCKER TOKEN
      run: 'curl  -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN
        }} -s -o test.json "https://auth.docker.io/token?service=registry.docker.io&scope=repository:janusgraph/janusgraph:pull,push"

        TOKEN=$(cat test.json | jq -r ''.token'')

        echo "DOCKER_SHORT_TOKEN=${TOKEN}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: EXTRACT VERSION
      run: 'MINOR_VERSION=$(echo "${{ github.event.release.tag_name }}" | grep -Eo
        ''[0-9]+\.[0-9]+'' | head -1)

        PATCH_VERSION=$(echo "${{ github.event.release.tag_name }}" | grep -Eo ''[0-9]+\.[0-9]+\.[0-9]+''
        | head -1)

        REVISION="$(git rev-parse --short HEAD)"

        echo "MINOR_VERSION=${MINOR_VERSION}" >> $GITHUB_ENV

        echo "PATCH_VERSION=${PATCH_VERSION}" >> $GITHUB_ENV

        echo "REVISION=${REVISION}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Run minor tag for ghcr.io
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: janusgraph/janusgraph
        tags: '${{ env.PATCH_VERSION }}

          ${{ env.MINOR_VERSION }}

          '
        target: ${{ env.PATCH_VERSION }}-${{ env.REVISION }}
    - continue-on-error: true
      name: Run minor tag for docker.io
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: index.docker.io
        repository: janusgraph/janusgraph
        tags: '${{ env.PATCH_VERSION }}

          ${{ env.MINOR_VERSION }}

          '
        target: ${{ env.PATCH_VERSION }}-${{ env.REVISION }}
        token: ${{ env.DOCKER_SHORT_TOKEN }}
    - continue-on-error: true
      if: env.MINOR_VERSION == '${{ env.LATEST_RELEASE }}'
      name: Run latest tag for ghcr.io
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: janusgraph/janusgraph
        tags: 'latest

          '
        target: ${{ env.PATCH_VERSION }}-${{ env.REVISION }}
    - continue-on-error: true
      if: env.MINOR_VERSION == '${{ env.LATEST_RELEASE }}'
      name: Run latest tag for docker.io
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: index.docker.io
        repository: janusgraph/janusgraph
        tags: 'latest

          '
        target: ${{ env.PATCH_VERSION }}-${{ env.REVISION }}
        token: ${{ env.DOCKER_SHORT_TOKEN }}
name: Apply docker tags to the official JanusGraph release
on:
  repository_dispatch:
    types: trigger-ga___docker-release-tags.yml
