jobs:
  lint-proto:
    name: buf lint
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ory/build-buf-action@v0
      with:
        bufArgs: lint --config janusgraph-grpc/buf.yaml ./janusgraph-grpc/src/main/proto/
        bufVersion: v0.56.0
name: Lint proto
on:
  repository_dispatch:
    types: trigger-ga___lint-proto.yml
